name: Acorda Motor Render
on:
  schedule:
    - cron: '*/14 * * * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Cutucar o servidor
        run: curl -s https://api-checkou-vitin.onrender.com
